services:
  - type: web
    name: feehost
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Rmmm:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
